# This rule is not used by the project aviator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the aviator.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aviator
    app.kubernetes.io/managed-by: kustomize
  name: aviatorpolicy-editor-role
rules:
- apiGroups:
  - aviator.example.com
  resources:
  - aviatorpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aviator.example.com
  resources:
  - aviatorpolicies/status
  verbs:
  - get
