//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviatorPolicy) DeepCopyInto(out *AviatorPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviatorPolicy.
func (in *AviatorPolicy) DeepCopy() *AviatorPolicy {
	if in == nil {
		return nil
	}
	out := new(AviatorPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AviatorPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviatorPolicyList) DeepCopyInto(out *AviatorPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AviatorPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviatorPolicyList.
func (in *AviatorPolicyList) DeepCopy() *AviatorPolicyList {
	if in == nil {
		return nil
	}
	out := new(AviatorPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AviatorPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviatorPolicySpec) DeepCopyInto(out *AviatorPolicySpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.LatencyThreshold = in.LatencyThreshold
	out.EvaluationInterval = in.EvaluationInterval
	in.Selection.DeepCopyInto(&out.Selection)
	if in.CircuitBreaker != nil {
		in, out := &in.CircuitBreaker, &out.CircuitBreaker
		*out = new(CircuitBreakerSpec)
		**out = **in
	}
	if in.Dampening != nil {
		in, out := &in.Dampening, &out.Dampening
		*out = new(DampeningSpec)
		**out = **in
	}
	if in.TargetPort != nil {
		in, out := &in.TargetPort, &out.TargetPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviatorPolicySpec.
func (in *AviatorPolicySpec) DeepCopy() *AviatorPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AviatorPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AviatorPolicyStatus) DeepCopyInto(out *AviatorPolicyStatus) {
	*out = *in
	in.LastEvaluationTime.DeepCopyInto(&out.LastEvaluationTime)
	if in.CircuitBrokenPods != nil {
		in, out := &in.CircuitBrokenPods, &out.CircuitBrokenPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodLatencies != nil {
		in, out := &in.PodLatencies, &out.PodLatencies
		*out = make([]PodLatencyInfo, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AviatorPolicyStatus.
func (in *AviatorPolicyStatus) DeepCopy() *AviatorPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AviatorPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectionPolicy) DeepCopyInto(out *SelectionPolicy) {
	*out = *in
	if in.TopN != nil {
		in, out := &in.TopN, &out.TopN
		*out = new(int32)
		**out = **in
	}
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectionPolicy.
func (in *SelectionPolicy) DeepCopy() *SelectionPolicy {
	if in == nil {
		return nil
	}
	out := new(SelectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerSpec) DeepCopyInto(out *CircuitBreakerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerSpec.
func (in *CircuitBreakerSpec) DeepCopy() *CircuitBreakerSpec {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DampeningSpec) DeepCopyInto(out *DampeningSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DampeningSpec.
func (in *DampeningSpec) DeepCopy() *DampeningSpec {
	if in == nil {
		return nil
	}
	out := new(DampeningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLatencyInfo) DeepCopyInto(out *PodLatencyInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLatencyInfo.
func (in *PodLatencyInfo) DeepCopy() *PodLatencyInfo {
	if in == nil {
		return nil
	}
	out := new(PodLatencyInfo)
	in.DeepCopyInto(out)
	return out
}
